card_to_action = {
    "SA": "Ace",
    "S2": "Two",
    "S3": "Three",
    "S4": "Four",
    "S5": "Five",
    "S6": "Six",
    "S7": "Seven",
    "S8": "Eight",
    "S9": "Nine",
    "ST": "Ten",
    "SJ": "Jack",
    "SQ": "Queen",
    "SK": "King",
    "HA": "Ace",
    "H2": "Two",
    "H3": "Three",
    "H4": "Four",
    "H5": "Five",
    "H6": "Six",
    "H7": "Seven",
    "H8": "Eight",
    "H9": "Nine",
    "HT": "Ten",
    "HJ": "Jack",
    "HQ": "Queen",
    "HK": "King",
    "DA": "Ace",
    "D2": "Two",
    "D3": "Three",
    "D4": "Four",
    "D5": "Five",
    "D6": "Six",
    "D7": "Seven",
    "D8": "Eight",
    "D9": "Nine",
    "DT": "Ten",
    "DJ": "Jack",
    "DQ": "Queen",
    "DK": "King",
    "CA": "Ace",
    "C2": "Two",
    "C3": "Three",
    "C4": "Four",
    "C5": "Five",
    "C6": "Six",
    "C7": "Seven",
    "C8": "Eight",
    "C9": "Nine",
    "CT": "Ten",
    "CJ": "Jack",
    "CQ": "Queen",
    "CK": "King",
}
action_to_card = {
    "Ace": ["SA", "HA", "DA", "CA"],
    "Two": ["S2", "H2", "D2", "C2"],
    "Three": ["S3", "H3", "D3", "C3"],
    "Four": ["S4", "H4", "D4", "C4"],
    "Five": ["S5", "H5", "D5", "C5"],
    "Six": ["S6", "H6", "D6", "C6"],
    "Seven": ["S7", "H7", "D7", "C7"],
    "Eight": ["S8", "H8", "D8", "C8"],
    "Nine": ["S9", "H9", "D9", "C9"],
    "Ten": ["ST", "HT", "DT", "CT"],
    "Jack": ["SJ", "HJ", "DJ", "CJ"],
    "Queen": ["SQ", "HQ", "DQ", "CQ"],
    "King": ["SK", "HK", "DK", "CK"],
    "Pickup": [],
}
