import rust_shed

a = rust_shed.Game(2, False)
print(a.get_num_players())
print(a.get_player_id())
a.init_game()
print(a.get_legal_actions())
# print(a.get_payoffs())
print(a.get_positions())
print(a.get_active_deck())
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
print(a.get_legal_actions())
# print(a.get_payoffs())
print(a.get_positions())
for c in a.get_active_deck():
    print(c.suit(), c.rank())