import rust_shed

def print_state(s):
    print("THE STATE")
    print(s.legal_actions)
    print(s.hand)
    print(s.live_deck_size)
    print(s.top_rank)
    print(s.top_rank_count)
    print(s.positions)
    print(s.current_player)
    print(s.unplayed_deck_size)
    print("*"*20)

a = rust_shed.Game(2, False)
print(a.get_num_players())
print(a.get_player_id())
a.init_game()
print(a.get_legal_actions())
# print(a.get_payoffs())
print(a.get_positions())
print(a.get_active_deck())
print(print_state(a.get_state()))
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
a.step(a.get_legal_actions()[0])
print(a.get_legal_actions())
print(print_state(a.get_state()))
print(a.get_positions())
for c in a.get_active_deck():
    print(c.suit, c.rank)
